language: rust
cache:
  cargo: true
  directories:
    - $HOME/.cache/apt

env:
  global:
    # This is the -Werror of Rust
    - RUSTFLAGS="--deny warnings"
    # Used for installation
    - LLVM_VERSION=9

install:
  # Install LLVM
  - sudo bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)" bash $LLVM_VERSION
  - sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-$LLVM_VERSION 100
  - sudo update-alternatives --install /usr/bin/llvm-config llvm-config /usr/bin/llvm-config-$LLVM_VERSION 100
  - sudo apt install libc++-dev libc++abi-dev --yes
  # No idea why we need to modify this here
  - PATH=/usr/bin:$PATH
  - llvm-config --version

script:
  # Make sure we compile
  - cargo build
  # Test compile any features
  - cargo build --features "cortex-m-attrs"
  # Now lets test the code benches
  - |
    cd code_benches
    python3 run.py
