language: rust
sudo: true
cache:
  cargo: true
  directories:
    - $HOME/.cache/apt

#addons:
#  apt:
#    packages:
#      - llvm-9-dev
#      - clang-9-dev
#      - libc++-dev
#      - libc++abi-dev

env:
  global:
    # This is the -Werror of Rust
    - RUSTFLAGS="--deny warnings"
    # Used for installation
    - LLVM_VERSION=9
    #- CC=/usr/bin/

install:
  # Install LLVM
  - echo $LLVM_VERSION
  - wget https://apt.llvm.org/llvm.sh
  - chmod +x llvm.sh
  - sudo ./llvm.sh $LLVM_VERSION
  #- sudo bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"
  #- llvm-config --version
  #- echo $LLVM_VERSION
  #- LLVM_VERSION=$(llvm-config --version | cut -d '.' -f 1)
  #- sudo update-alternatives --install /usr/bin/cc cc /usr/bin/clang 100
  - sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-$LLVM_VERSION 100
  - sudo update-alternatives --install /usr/bin/llvm-config llvm-config /usr/bin/llvm-config-$LLVM_VERSION 100
  - sudo apt install libc++-dev libc++abi-dev --yes
  - clang --version
  - llvm-config --version

script:
  # Make sure we compile
  - cargo build
  # Test compile any features
  - cargo build --features "cortex-m-attrs"

