language: rust

env:
  global:
    # This is the -Werror of Rust
    - RUSTFLAGS="--deny warnings"

install:
  - ./install_deb.sh

script:
  # Make sure we compile
  - cargo build --verbose
  # Test compile any features
  - cargo build --features "cortex-m-attrs"

